### ISSUE TITLE
Error messages propogated to HTML content

### ISSUE THREAD

**Issue by jerinphilip** [jelmervdl/firefox-translations#9]
Is the below big-reds intended?

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/727292/154855777-4b18c722-4a70-4f2c-81ff-425a6dc5f7f3.png">

**Comment by jelmervdl** [comment]
These errors are from Wikipedia itself! If you go in any other browser, or with the extension turned off, to https://es.wikipedia.org/wiki/Santiago_de_Chile, you'll also see them.

(They do appear to be correctly translated by the extension, even the qoutes go from _«censo2002»_ to _"center2002"_ hehehe)
